[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dummy-package"
version = "0.1.0"
description = "Dummy package for LangGraph Cloud build compatibility"
authors = [{name = "LangGraph Cloud"}]
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
