[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "placeholder-pkg"
version = "0.0.1"
description = "No-op placeholder package to satisfy /deps/* install step"
readme = "README.md"
requires-python = ">=3.9"

[tool.hatch.build.targets.wheel]
packages = ["src/placeholder_pkg"]
